CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
As discussed on the mailing list.
@niczem I added your email as contact address, hope that's okay.
=> Add contributing document and code of conduct

src/app/app.component.html, src/app/app.module.ts, src/app/components/create-case-form/create-case-form.component.css, src/app/components/create-case-form/create-case-form.component.html, src/app/components/create-case-form/create-case-form.component.ts, src/app/components/modalplaceholder/modalplaceholder.component.html, src/app/components/modalplaceholder/modalplaceholder.component.spec.ts, src/app/components/modalplaceholder/modalplaceholder.component.ts, src/app/components/top-nav/top-nav.component.html, src/app/components/top-nav/top-nav.component.ts, src/app/interfaces/case.ts, src/app/interfaces/modalcontainer.ts, src/app/services/modal.service.spec.ts, src/app/services/modal.service.ts, src/app/services/pouch.service.ts, src/app/services/vehicles.service.ts
I implemented a simple Modal-Service that allows us to put any Component in a Modal and show it as Overlay. I mainly followed the tutorial on that page:
http://blog.brecht.io/Modals-in-angular2/
A sample Modal can be seen in components/create-case
=> Modal service

src/app/services/pouch.service.ts, src/app/services/vehicles.service.ts
I would like to also move the main part of the getVehicles function to the PouchService (see PouchService.get() ), but I have problems to pass the promise to the VehicleService
=> handleChange function removed from vehicleService

src/app/services/auth.service.ts, src/css/site.css
... roboto is not used in the whole repo
=> Google font completely removed

data/seeds/README.md
This contains a list of users and their passwords.
=> Start a README file for the database seeds

angular-cli.json
=> Add missing img folder to build

.editorconfig, package.json
Run the fmt script before testing and building the project.
I will do another PR to format our existing source code.
=> Add typescript-formatter and adjust editorconfig

package.json
App tested on Linux and Windows.
=> Update to electron-builder 15.3.0

src/app/components/left-nav/left-nav.component.html, src/app/components/left-nav/left-nav.component.ts, src/app/components/map-view/map-view.component.ts, src/app/services/locations.service.ts, src/app/services/map.service.ts
- remove markers with the same id on insert, to allow for primitive updates.
- get location of cases and vehicles from LocationService and show them on the map.
- first steps towards filtering.
=> show cases/vehicles at location on map

package.json, script/location_services/config.js, script/location_services/location_service.js
travis fails because of an error which is fixed in this pull request:
https://github.com/sea-watch/SAR-Client/pull/55
=> Location service

.travis.yml
Enables macOS builds and deployments on Travis-CI.
=> Enable macOS builds on travis

src/app/components/case-list/case-list.component.css, src/app/components/case-list/case-list.component.html, src/app/components/create-case-form/create-case-form.component.css, src/app/components/create-case-form/create-case-form.component.html, src/app/components/top-nav/top-nav.component.html, src/css/site.css, src/css/style.css
Input also some demo-content as "Meta" or "Case-ID".
=> First style changes for the Case-View and Navigation

README.md, src/app/components/case-list/case-list.component.ts, src/app/components/create-case-form/create-case-form.component.css, src/app/components/create-case-form/create-case-form.component.html, src/app/components/create-case-form/create-case-form.component.ts, src/app/interfaces/listener.ts, src/app/services/cases.service.ts, src/app/services/locations.service.ts, src/app/services/pouch.service.ts
=> Fix case bugs

src/app/components/create-case-form/create-case-form.component.html, src/app/components/create-case-form/create-case-form.component.ts, src/app/interfaces/case.ts, src/app/interfaces/location.ts, src/app/services/cases.service.ts
=> Add reported by to cases and locations

data/seeds/versions.json, script/db-seed-import.sh
invalid json fixed
Delete command added before seeding a new database
(https://github.com/sea-watch/SAR-Client/pull/85 should be reviewed first)
=> Scripts updated

data/seeds/cases.json, data/seeds/versions.json, package.json, script/db-seed-import.sh, src/app/app.component.html, src/app/components/case-list/case-list.component.css, src/app/components/case-list/case-list.component.html, src/app/components/case-list/case-list.component.spec.ts, src/app/components/case-list/case-list.component.ts, src/app/components/create-case-form/create-case-form.component.html, src/app/components/left-nav/left-nav.component.html, src/app/components/left-nav/left-nav.component.ts, src/app/components/log-in/log-in.component.html, src/app/components/top-nav/top-nav.component.html, src/app/interfaces/boat-condition.ts, src/app/interfaces/case.ts, src/app/services/cases.service.ts, src/css/site.css, src/css/style.css
Some minor style changes and connected model changes in the case model
-The boatcondition can only be "People in water/No people in water"
-Added "osc", and "createdAt" to the case model
-Multiple state filters are possible instead of a single one
=> Style changes and changes in the case model

src/app/components/case-list/case-list.component.ts, src/app/components/create-case-form/create-case-form.component.ts, src/app/components/left-nav/left-nav.component.html, src/app/components/left-nav/left-nav.component.ts, src/app/components/map-view/map-view.component.ts, src/app/services/locations.service.ts, src/app/services/map.service.ts, src/app/services/pouch.service.ts
Updating the map every minute, relatively ugly with an interval.
Also putting the position shown in the popup in a human readable format and adding the time the location was recorded.
=> update ship position on map

src/app/components/case-list/case-list.component.ts, src/app/components/settings/settings.component.ts, src/app/services/pouch.service.ts
show the settings on application startup
case-list sorting fixed
=> Mixed fixes

src/app/components/map-view/map-view.component.ts
Otherwise this will re-draw in the background when leaving the map view.
=> Destroy vehicle draw interval when leaving map view

src/app/components/create-case-form/create-case-form.component.html
Otherwise all changes will be lost anyway. With that we can force the editor to first reload the changes.
=> Disable submit button when a conflict is detected.

src/app/services/auth.service.ts, src/index.html, src/index.js
=> logout fixed

src/app/app.component.ts, src/app/ipc-messages.ts, src/app/services/electron-ipc.service.ts, src/index.html, src/index.js
**EXPERIMENT - DO NOT MERGE!**
This exposes the electron IPC mechanism to angular via the ElectronIpcService.
Might be used as an example to get position updates from the main process into the angular application to be able to use nodejs APIs like child processes.
=> [Experiment] Listen for position updates from the main process

src/app/components/case-list/case-list.component.html, src/app/components/chat/chat.component.html, src/app/components/create-case-form/create-case-form.component.html, src/app/services/cases.service.ts, src/app/services/map.service.ts
- date beautified (fixes #121)
- map zoom set to max (fixes #154)
- filter selection fixed (fixes #123)
=> Multiple fixes

src/app/services/map.service.ts
=> #154 fixed

package.json, script/services/mail_service.js
Possibility for tracking via iridium go tracking mails added.
=> Iridium location service

script/services/example_config.js, script/services/location_service.js, script/services/marinetraffic.js
(the epak service had a problem with the waterfall callbacks when sw2 wasn't the last vehicle inside the query result)
=> Location service for ais added, epak service improved

src/app/components/map-view/map-view.component.ts, src/app/services/map.service.ts, src/css/style.css
colors and titles added to vehicle markersM
=> Marker colors added
